services:
  sqlserver:
    build:
      context: devops
      dockerfile: server.Dockerfile
      args:
        MSSQL_VERSION: "2022"
    environment:
      SA_PASSWORD: "L0calTesting!"
      ACCEPT_EULA: "Y"
    env_file:
      - test.env
    ports:
      - "1433:1433"
